update PCF set PCF_WIDTH=16 where PCF_NAME="NIX00123";
update PCF set PCF_WIDTH=8 where PCF_NAME="ZZPAD008";
update PCF set PCF_WIDTH=16 where PCF_NAME='ZZPAD016';
update PCF set PCF_WIDTH=24 where PCF_NAME='ZZPAD024';
update PCF set PCF_WIDTH=32 where PCF_NAME='ZZPAD032';
INSERT INTO tblConfigS2KParameterTypes VALUES(10,13,13,'T','Relative Time CUC format (3 bytes coarse time, 2 bytes fine time)','40','1','1','Relative time CUC format');
INSERT INTO tblConfigS2KParameterTypes VALUES(10,14,14,'T','Relative Time CUC format (3 bytes coarse time, 3 bytes fine time)','48','1','1','Relative time CUC format');
INSERT INTO tblConfigS2KParameterTypes VALUES(10,15,15,'T','Relative Time CUC format (4 bytes coarse time)','32','1','1','Relative time CUC format');
INSERT INTO tblConfigS2KParameterTypes VALUES(10,16,16,'T','Relative Time CUC format (4 bytes coarse time, 1 byte fine time)','40','1','1','Relative time CUC format');
INSERT INTO tblConfigS2KParameterTypes VALUES(10,17,17,'T','Relative Time CUC format (4 bytes coarse time, 2 bytes fine time)','48','1','1','Relative time CUC format');
INSERT INTO tblConfigS2KParameterTypes VALUES(11,0,0,'D','Deduced','Variable','1','1','Deduced Parameters');
INSERT INTO tblConfigS2KParameterTypes VALUES(13,0,0,NULL,NULL,NULL,'0','0','Saved Synthetic Parameter');
INSERT INTO tblConfigS2KParameterTypes VALUES(0,0,0,NULL,NULL,NULL,'0','0',NULL);
INSERT INTO tblConfigS2KParameterTypes VALUES(1,0,0,'U','Unsigned Integer','1','1','1','Boolean Parameter');
INSERT INTO tblConfigS2KParameterTypes VALUES(3,12,12,'U','Unsigned Integer','16','1','1','Unsigned Integer Parameter');
INSERT INTO tblConfigS2KParameterTypes VALUES(3,0,0,'U','Unsigned Integer','4','1','1','Unsigned Integer Parameter');
INSERT INTO tblConfigS2KParameterTypes VALUES(3,1,1,'U','Unsigned Integer','5','1','1','Unsigned Integer Parameter');
INSERT INTO tblConfigS2KParameterTypes VALUES(3,2,2,'U','Unsigned Integer','6','1','1','Unsigned Integer Parameter');
INSERT INTO tblConfigS2KParameterTypes VALUES(3,3,3,'U','Unsigned Integer','7','1','1','Unsigned Integer Parameter');
INSERT INTO tblConfigS2KParameterTypes VALUES(3,4,4,'U','Unsigned Integer','8','1','1','Unsigned Integer Parameter');
INSERT INTO tblConfigS2KParameterTypes VALUES(3,5,5,'U','Unsigned Integer','9','1','1','Unsigned Integer Parameter');
INSERT INTO tblConfigS2KParameterTypes VALUES(3,6,6,'U','Unsigned Integer','10','1','1','Unsigned Integer Parameter');
INSERT INTO tblConfigS2KParameterTypes VALUES(3,7,7,'U','Unsigned Integer','11','1','1','Unsigned Integer Parameter');
INSERT INTO tblConfigS2KParameterTypes VALUES(3,8,8,'U','Unsigned Integer','12','1','1','Unsigned Integer Parameter');
INSERT INTO tblConfigS2KParameterTypes VALUES(3,9,9,'U','Unsigned Integer','13','1','1','Unsigned Integer Parameter');
INSERT INTO tblConfigS2KParameterTypes VALUES(3,10,10,'U','Unsigned Integer','14','1','1','Unsigned Integer Parameter');
INSERT INTO tblConfigS2KParameterTypes VALUES(3,11,11,'U','Unsigned Integer','15','1','1','Unsigned Integer Parameter');
INSERT INTO tblConfigS2KParameterTypes VALUES(3,13,13,'U','Unsigned Integer','24','1','1','Unsigned Integer Parameter');
INSERT INTO tblConfigS2KParameterTypes VALUES(3,14,14,'U','Unsigned Integer','32','1','1','Unsigned Integer Parameter');
INSERT INTO tblConfigS2KParameterTypes VALUES(3,15,15,'U','Unsigned Integer','48','0','0','Unsigned Integer Parameter (not supported by S2K)');
INSERT INTO tblConfigS2KParameterTypes VALUES(3,16,16,'U','Unsigned Integer','64','0','0','Unsigned Integer Parameter (not supported by S2K)');
INSERT INTO tblConfigS2KParameterTypes VALUES(2,1,32,'U','Unsigned Integer','PFC bits','1','1','Enumerated Parameter');
INSERT INTO tblConfigS2KParameterTypes VALUES(8,0,0,'A','ASCII String','Variable','1','1','Variable-Length Character String');
INSERT INTO tblConfigS2KParameterTypes VALUES(8,1,99999,'A','ASCII String','PFC octets','1','1','Fixed-Length Character String');
INSERT INTO tblConfigS2KParameterTypes VALUES(4,12,12,'I','Signed Integer','16','1','1','Signed Integer Parameter');
INSERT INTO tblConfigS2KParameterTypes VALUES(4,0,0,'I','Signed Integer','4','1','1','Signed Integer Parameter');
INSERT INTO tblConfigS2KParameterTypes VALUES(4,1,1,'I','Signed Integer','5','1','1','Signed Integer Parameter');
INSERT INTO tblConfigS2KParameterTypes VALUES(4,2,2,'I','Signed Integer','6','1','1','Signed Integer Parameter');
INSERT INTO tblConfigS2KParameterTypes VALUES(4,3,3,'I','Signed Integer','7','1','1','Signed Integer Parameter');
INSERT INTO tblConfigS2KParameterTypes VALUES(4,4,4,'I','Signed Integer','8','1','1','Signed Integer Parameter');
INSERT INTO tblConfigS2KParameterTypes VALUES(4,5,5,'I','Signed Integer','9','1','1','Signed Integer Parameter');
INSERT INTO tblConfigS2KParameterTypes VALUES(4,6,6,'I','Signed Integer','10','1','1','Signed Integer Parameter');
INSERT INTO tblConfigS2KParameterTypes VALUES(4,7,7,'I','Signed Integer','11','1','1','Signed Integer Parameter');
INSERT INTO tblConfigS2KParameterTypes VALUES(4,8,8,'I','Signed Integer','12','1','1','Signed Integer Parameter');
INSERT INTO tblConfigS2KParameterTypes VALUES(4,9,9,'I','Signed Integer','13','1','1','Signed Integer Parameter');
INSERT INTO tblConfigS2KParameterTypes VALUES(4,10,10,'I','Signed Integer','14','1','1','Signed Integer Parameter');
INSERT INTO tblConfigS2KParameterTypes VALUES(4,11,11,'I','Signed Integer','15','1','1','Signed Integer Parameter');
INSERT INTO tblConfigS2KParameterTypes VALUES(4,13,13,'I','Signed Integer','24','1','1','Signed Integer Parameter');
INSERT INTO tblConfigS2KParameterTypes VALUES(4,14,14,'I','Signed Integer','32','1','1','Signed Integer Parameter');
INSERT INTO tblConfigS2KParameterTypes VALUES(4,15,15,'I','Signed Integer','48','0','0','Signed Integer Parameter (not supported by S2K)');
INSERT INTO tblConfigS2KParameterTypes VALUES(4,16,16,'I','Signed Integer','64','0','0','Signed Integer Parameter (not supported by S2K)');
INSERT INTO tblConfigS2KParameterTypes VALUES(5,1,1,'R','Simple Precision Real (IEEE)','32','1','1','Simple Precision Real Parameter');
INSERT INTO tblConfigS2KParameterTypes VALUES(5,2,2,'R','Double Precision Real (IEEE)','64','1','1','Double Precision Real Parameter');
INSERT INTO tblConfigS2KParameterTypes VALUES(5,3,3,'R','Simple Precision Real (MIL)','32','0','1','32-bit Floating Point Parameter (MIL STD 1750 A)');
INSERT INTO tblConfigS2KParameterTypes VALUES(5,4,4,'R','Extended Precision Real (MIL)','48','0','1','48-bit Floating Point Parameter (MIL STD 1750 A)');
INSERT INTO tblConfigS2KParameterTypes VALUES(6,0,0,'B','Bit String','Variable','0','0','Variable-Length Bit String');
INSERT INTO tblConfigS2KParameterTypes VALUES(6,1,32,'U','Unsigned Integer','PFC bits','1','1','PUS Bit-String Parameter');
INSERT INTO tblConfigS2KParameterTypes VALUES(7,0,0,'O','Octet String','Variable','1','1','Variable-Length Octet String');
INSERT INTO tblConfigS2KParameterTypes VALUES(7,1,99999,'O','Octet String','PFC octets','1','1','Fixed-Length Octet String');
INSERT INTO tblConfigS2KParameterTypes VALUES(9,17,17,'T','Absolute Time CUC format (4 bytes coarse time, 2 bytes fine time)','48','1','1','Absolute time CUC format');
INSERT INTO tblConfigS2KParameterTypes VALUES(9,0,0,'T','Absolute Time (CUC or CDS format) with p-field','Variable','0','0','Full definition of an absolute time based on ist p-field');
INSERT INTO tblConfigS2KParameterTypes VALUES(9,1,1,'T','Absolute Time CDS format without microseconds (6 bytes without p-field)','48','0','0','Absolute time CDS format without microseconds');
INSERT INTO tblConfigS2KParameterTypes VALUES(9,2,2,'T','Absolute Time CDS format with microseconds (8 bytes without p-field)','64','1','1','Absolute time CDS format with microseconds (TC params only)');
INSERT INTO tblConfigS2KParameterTypes VALUES(9,3,3,'T','Absolute Time CUC format (1 byte coarse time)','8','1','1','Absolute time CUC format');
INSERT INTO tblConfigS2KParameterTypes VALUES(9,4,4,'T','Absolute Time CUC format (1 byte coarse time, 1 byte fine time)','16','1','1','Absolute time CUC format');
INSERT INTO tblConfigS2KParameterTypes VALUES(9,5,5,'T','Absolute Time CUC format (1 byte coarse time, 2 bytes fine time)','24','1','1','Absolute time CUC format');
INSERT INTO tblConfigS2KParameterTypes VALUES(9,6,6,'T','Absolute Time CUC format (1 byte coarse time, 3 bytes fine time)','32','1','1','Absolute time CUC format');
INSERT INTO tblConfigS2KParameterTypes VALUES(9,7,7,'T','Absolute Time CUC format (2 bytes coarse time)','16','1','1','Absolute time CUC format');
INSERT INTO tblConfigS2KParameterTypes VALUES(9,8,8,'T','Absolute Time CUC format (2 bytes coarse time, 1 byte fine time)','24','1','1','Absolute time CUC format');
INSERT INTO tblConfigS2KParameterTypes VALUES(9,18,18,'T','Absolute Time CUC format (4 bytes coarse time, 3 bytes fine time)','56','1','1','Absolute time CUC format');
INSERT INTO tblConfigS2KParameterTypes VALUES(9,9,9,'T','Absolute Time CUC format (2 bytes coarse time, 2 bytes fine time)','32','1','1','Absolute time CUC format');
INSERT INTO tblConfigS2KParameterTypes VALUES(9,10,10,'T','Absolute Time CUC format (2 bytes coarse time, 3 bytes fine time)','40','1','1','Absolute time CUC format');
INSERT INTO tblConfigS2KParameterTypes VALUES(9,11,11,'T','Absolute Time CUC format (3 bytes coarse time)','24','1','1','Absolute time CUC format');
INSERT INTO tblConfigS2KParameterTypes VALUES(9,12,12,'T','Absolute Time CUC format (3 bytes coarse time, 1 byte fine time)','32','1','1','Absolute time CUC format');
INSERT INTO tblConfigS2KParameterTypes VALUES(9,13,13,'T','Absolute Time CUC format (3 bytes coarse time, 2 bytes fine time)','40','1','1','Absolute time CUC format');
INSERT INTO tblConfigS2KParameterTypes VALUES(9,14,14,'T','Absolute Time CUC format (3 bytes coarse time, 3 bytes fine time)','48','1','1','Absolute time CUC format');
INSERT INTO tblConfigS2KParameterTypes VALUES(9,15,15,'T','Absolute Time CUC format (4 bytes coarse time)','32','1','1','Absolute time CUC format');
INSERT INTO tblConfigS2KParameterTypes VALUES(9,16,16,'T','Absolute Time CUC format (4 bytes coarse time, 1 byte fine time)','40','1','1','Absolute time CUC format');
INSERT INTO tblConfigS2KParameterTypes VALUES(10,3,3,'T','Relative Time CUC format (1 byte coarse time)','8','1','1','Relative time CUC format');
INSERT INTO tblConfigS2KParameterTypes VALUES(10,18,18,'T','Relative Time CUC format (4 bytes coarse time, 3 bytes fine time)','56','1','1','Relative time CUC format');
INSERT INTO tblConfigS2KParameterTypes VALUES(10,4,4,'T','Relative Time CUC format (1 byte coarse time, 1 byte fine time)','16','1','1','Relative time CUC format');
INSERT INTO tblConfigS2KParameterTypes VALUES(10,5,5,'T','Relative Time CUC format (1 byte coarse time, 2 bytes fine time)','24','1','1','Relative time CUC format');
INSERT INTO tblConfigS2KParameterTypes VALUES(10,6,6,'T','Relative Time CUC format (1 byte coarse time, 3 bytes fine time)','32','1','1','Relative time CUC format');
INSERT INTO tblConfigS2KParameterTypes VALUES(10,7,7,'T','Relative Time CUC format (2 bytes coarse time)','16','1','1','Relative time CUC format');
INSERT INTO tblConfigS2KParameterTypes VALUES(10,8,8,'T','Relative Time CUC format (2 bytes coarse time, 1 byte fine time)','24','1','1','Relative time CUC format');
INSERT INTO tblConfigS2KParameterTypes VALUES(10,9,9,'T','Relative Time CUC format (2 bytes coarse time, 2 bytes fine time)','32','1','1','Relative time CUC format');
INSERT INTO tblConfigS2KParameterTypes VALUES(10,10,10,'T','Relative Time CUC format (2 bytes coarse time, 3 bytes fine time)','40','1','1','Relative time CUC format');
INSERT INTO tblConfigS2KParameterTypes VALUES(10,11,11,'T','Relative Time CUC format (3 bytes coarse time)','24','1','1','Relative time CUC format');
INSERT INTO tblConfigS2KParameterTypes VALUES(10,12,12,'T','Relative Time CUC format (3 bytes coarse time, 1 byte fine time)','32','1','1','Relative time CUC format');
